name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["2.7", "3.0", truffleruby-head]

    env:
      RUBYOPT: "-W:no-experimental"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec
      - name: Perform type check
        run: bundle exec steep check
      - name: Lint
        run: bundle exec rubocop
      - name: Check documentation coverage
        run: bundle exec yard stats --list-undoc
